Fix error on CI nightly tests
Error: Failed to execute command: 'chmod 777...
Issue probably appeared, because of:
https://github.com/OXID-eSales/paypal/commit/bd7e0c0dd95d3d0276c4127d2844c26a129a05d8#diff-2fe90eeec6ec78d8c609e94a9315d11cR55